export const CENTERFREQUENCY_CHANGE = 'CENTERFREQUENCY_CHANGE'
export const FREQUENCY_CHANGE = 'FREQUENCY_CHANGE'
export const BANDWIDTH_CHANGE = 'BANDWIDTH_CHANGE'
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES'
