// radio control
export const CENTERFREQUENCY_CHANGE = 'CENTERFREQUENCY_CHANGE'
export const FREQUENCY_CHANGE = 'FREQUENCY_CHANGE'
export const BANDWIDTH_CHANGE = 'BANDWIDTH_CHANGE'
export const POWER_CHANGE = 'POWER_CHANGE'
export const GAIN_CHANGE = 'GAIN_CHANGE'
export const MODULATION_CHANGE = 'MODULATION_CHANGE'
export const SAMPLERATE_CHANGE = 'SAMPLERATE_CHANGE'
export const AUDIORATE_CHANGE = 'AUDIORATE_CHANGE'
export const TUNERGAIN_CHANGE = 'TUNERGAIN_CHANGE'
export const STEPFREQUENCY_CHANGE = 'STEPFREQUENCY_CHANGE'
// devices
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES'
export const RECEIVE_CAPABILITIES = 'RECEIVE_CAPABILITIES'
